# Generated by Django 5.2.14 on 2026-05-15 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administracion', '0001_initial'),
        ('sitios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mae_repusuarios',
            name='cod_sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cod_sede', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='mae_repusuarios',
            name='mae_reportes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mae_reportes', to='Administracion.mae_reportes'),
        ),
        migrations.AddField(
            model_name='mae_subgruporeportes',
            name='mae_gruporeportes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Administracion.mae_gruporeportes'),
        ),
        migrations.AddField(
            model_name='mae_reportes',
            name='mae_subgruporeportes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Administracion.mae_subgruporeportes'),
        ),
        migrations.AddField(
            model_name='mae_repparametros',
            name='mae_tiposcampo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Administracion.mae_tiposcampo'),
        ),
        migrations.AlterUniqueTogether(
            name='mae_repusuarios',
            unique_together={('cod_sede', 'mae_reportes', 'cod_usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='mae_subgruporeportes',
            unique_together={('mae_gruporeportes', 'nom_subgrupo')},
        ),
        migrations.AlterUniqueTogether(
            name='mae_repparametros',
            unique_together={('mae_reportes', 'parametro')},
        ),
    ]
