# Generated by Django 5.2.14 on 2026-05-15 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinico', '0005_initial'),
        ('contratacion', '0003_initial'),
        ('planta', '0002_initial'),
        ('referencia', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarioscontacto'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='convenio1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convenio22', to='contratacion.convenios'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='convenio2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convenio23', to='contratacion.convenios'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='cups1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups28', to='clinico.tiposexamen'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='cups2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups27', to='clinico.tiposexamen'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='cups3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups26', to='clinico.tiposexamen'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='cups4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups25', to='clinico.tiposexamen'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='cups5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups24', to='clinico.tiposexamen'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='cups6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups23', to='clinico.tiposexamen'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria9', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='dxEgreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='dxIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx27', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cups22', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='regimerReferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx26', to='clinico.regimenes'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.servicios'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
    ]
