# Generated by Django 5.2.14 on 2026-05-15 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartera', '0001_initial'),
        ('contratacion', '0002_initial'),
        ('facturacion', '0002_initial'),
        ('planta', '0001_initial'),
        ('rips', '0001_initial'),
        ('sitios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica7648', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='caja',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm335', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='caja',
            name='usuarioEntrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7397', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='caja',
            name='usuarioRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7597', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='caja',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7297', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='caja',
            name='usuarioSuperviza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7497', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='cartera',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Empresas764578', to='facturacion.empresas'),
        ),
        migrations.AddField(
            model_name='cartera',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.facturacion'),
        ),
        migrations.AddField(
            model_name='cartera',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica784145', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='formaspagos',
            name='codigoRips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiposPagosMod7645', to='rips.ripstipospagomoderador'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='estadoRadicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estadoGloas02', to='cartera.estadosglosas'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='estadoRecepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estadoGlosa01', to='cartera.estadosglosas'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='ripsEnvio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.ripsenvios'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica764', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm10', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='usuarioRecepcion',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepcion01', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario987', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='usuarioRespuesta',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuesta01', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='glosasconceptoespecifico',
            name='conceptoGeneral',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.glosasconceptogeneral'),
        ),
        migrations.AddField(
            model_name='glosasdetalle',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturacion10322', to='facturacion.facturacion'),
        ),
        migrations.AddField(
            model_name='glosasdetalle',
            name='glosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.glosas'),
        ),
        migrations.AddField(
            model_name='glosasdetalle',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7423', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='glosasDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.glosasdetalle'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='ripsConsultas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsCons01', to='rips.ripsconsultas'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='ripsMedicamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsMedic01', to='rips.ripsmedicamentos'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='ripsOtrosServicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsOtros01', to='rips.ripsotrosservicios'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='ripsProcedimientos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsProced01', to='rips.ripsprocedimientos'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos10', to='rips.ripstipos'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario79533', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='motivosglosas',
            name='conceptoEspecifico',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.glosasconceptoespecifico'),
        ),
        migrations.AddField(
            model_name='motivosglosas',
            name='conceptoGeneral',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.glosasconceptogeneral'),
        ),
        migrations.AddField(
            model_name='glosasdetallerips',
            name='motivoGlosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.motivosglosas'),
        ),
        migrations.AddField(
            model_name='notascredito',
            name='estadoRadicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estadoNotaCredito02', to='cartera.estadosglosas'),
        ),
        migrations.AddField(
            model_name='notascredito',
            name='estadoRecepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estadoNotaCredito01', to='cartera.estadosglosas'),
        ),
        migrations.AddField(
            model_name='notascredito',
            name='ripsEnvio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.ripsenvios'),
        ),
        migrations.AddField(
            model_name='notascredito',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica765', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='notascredito',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm11', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='notascredito',
            name='usuarioRecepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepcion16', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='notascredito',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario799', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='notascredito',
            name='usuarioRespuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuesta15', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='notascreditodetalle',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturacion103', to='facturacion.facturacion'),
        ),
        migrations.AddField(
            model_name='notascreditodetalle',
            name='notaCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.notascredito'),
        ),
        migrations.AddField(
            model_name='notascreditodetalle',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario796', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='notaCreditoDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.notascreditodetalle'),
        ),
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='ripsConsultas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsCons0xy1', to='rips.ripsconsultas'),
        ),
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='ripsMedicamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsMedic0xy1', to='rips.ripsmedicamentos'),
        ),
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='ripsOtrosServicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsOtros0xy2', to='rips.ripsotrosservicios'),
        ),
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='ripsProcedimientos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsProced0xy1', to='rips.ripsprocedimientos'),
        ),
        migrations.AddField(
            model_name='notascreditodetallerips',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario7956', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='notasdebito',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.empresas'),
        ),
        migrations.AddField(
            model_name='notasdebito',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturacion07', to='facturacion.facturacion'),
        ),
        migrations.AddField(
            model_name='notasdebito',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.ripsdetalle'),
        ),
        migrations.AddField(
            model_name='notasdebito',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos12', to='rips.ripstipos'),
        ),
        migrations.AddField(
            model_name='notasdebito',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica760', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='notasdebito',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm12', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='notasdebito',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario797', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.caja'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratacion.convenios'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento77', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='formaPago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.formaspagos'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica7645', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm05', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='pagosempresas',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EmpresasPagos73645', to='facturacion.empresas'),
        ),
        migrations.AddField(
            model_name='pagosempresas',
            name='formaPago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.formaspagos'),
        ),
        migrations.AddField(
            model_name='pagosempresas',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica764145', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='pagosempresas',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm095', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='pagosempresasdetalle',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.facturacion'),
        ),
        migrations.AddField(
            model_name='pagosempresasdetalle',
            name='pagosEmpresas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EmpresasPagos7646', to='cartera.pagosempresas'),
        ),
        migrations.AddField(
            model_name='pagosempresasdetalle',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm09588', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='pagosfacturas',
            name='facturaAplicada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.facturacion'),
        ),
        migrations.AddField(
            model_name='pagosfacturas',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.pagos'),
        ),
        migrations.AddField(
            model_name='pagosfacturas',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica7647', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='pagosfacturas',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm06', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='radicaciones',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica762', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='radicaciones',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm08', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='radicaciones',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AddField(
            model_name='remisiones',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica763', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='remisiones',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='tipoGlosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estadoGlosa01', to='cartera.tiposglosas'),
        ),
        migrations.AddField(
            model_name='notascredito',
            name='tiposNota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiposNotasCredito01', to='cartera.tiposnotas'),
        ),
        migrations.AddField(
            model_name='glosas',
            name='tiposNota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiposNotasGlosa01', to='cartera.tiposnotas'),
        ),
        migrations.AddField(
            model_name='pagosempresas',
            name='tipoPago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.tipospagos'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='tipoPago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.tipospagos'),
        ),
    ]
