# Generated by Django 5.2.14 on 2026-05-15 23:03

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cirugia', '0003_initial'),
        ('clinico', '0005_initial'),
        ('facturacion', '0003_initial'),
        ('planta', '0002_initial'),
        ('rips', '0002_initial'),
        ('sitios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencias',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoDepAct', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='dependencias',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='dependencias',
            name='dependenciasTipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.dependenciastipo'),
        ),
        migrations.AddField(
            model_name='historialdependencias',
            name='dependencias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.dependencias'),
        ),
        migrations.AddField(
            model_name='historialdependencias',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentohistorialDep', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='historialdependencias',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='historialdependencias',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.departamentos'),
        ),
        migrations.AddField(
            model_name='municipios',
            name='ripsMunicipios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.ripsmunicipios'),
        ),
        migrations.AddField(
            model_name='localidades',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.municipios'),
        ),
        migrations.AddField(
            model_name='departamentos',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.paises'),
        ),
        migrations.AddField(
            model_name='salas',
            name='dependenciaTipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.dependenciastipo'),
        ),
        migrations.AddField(
            model_name='salas',
            name='estadoSala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.estadossalas'),
        ),
        migrations.AddField(
            model_name='disponibilidadsalas',
            name='salas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.salas'),
        ),
        migrations.AddField(
            model_name='sedesclinica',
            name='ciudades',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='departamentos', chained_model_field='departamentos', on_delete=django.db.models.deletion.CASCADE, to='sitios.ciudades'),
        ),
        migrations.AddField(
            model_name='sedesclinica',
            name='departamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.departamentos'),
        ),
        migrations.AddField(
            model_name='sedesclinica',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empre99', to='facturacion.empresas'),
        ),
        migrations.AddField(
            model_name='sedesclinica',
            name='prefijoDian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.prefijosdian'),
        ),
        migrations.AddField(
            model_name='salas',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='dependencias',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='bodegas',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='serviciosadministrativos',
            name='dependenciaTipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.dependenciastipo'),
        ),
        migrations.AddField(
            model_name='serviciosadministrativos',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='salas',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='dependencias',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='bodegas',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='serviciossedes',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='serviciossedes',
            name='servicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.servicios'),
        ),
        migrations.AddField(
            model_name='dependencias',
            name='serviciosSedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serviciosSedes1', to='sitios.serviciossedes'),
        ),
        migrations.AddField(
            model_name='subserviciossedes',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='subserviciossedes',
            name='serviciosSedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.serviciossedes'),
        ),
        migrations.AddField(
            model_name='dependencias',
            name='subServiciosSedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.subserviciossedes'),
        ),
        migrations.AddField(
            model_name='salas',
            name='tipoSala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.tipossalas'),
        ),
        migrations.AddField(
            model_name='ubicaciones',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='serviciosadministrativos',
            name='ubicaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.ubicaciones'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidadsalas',
            unique_together={('salas', 'fecha', 'desdeHora', 'hastaHora')},
        ),
        migrations.AlterUniqueTogether(
            name='serviciossedes',
            unique_together={('sedesClinica', 'servicios')},
        ),
        migrations.AlterUniqueTogether(
            name='subserviciossedes',
            unique_together={('sedesClinica', 'serviciosSedes', 'subServiciosSedes')},
        ),
        migrations.AlterUniqueTogether(
            name='dependencias',
            unique_together={('tipoDoc', 'documento', 'consec', 'disponibilidad')},
        ),
    ]
