# Generated by Django 2.1.15 on 2026-03-09 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0002_auto_20260309_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estancias',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='estancias',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='estancias',
            name='tipoEstancia',
        ),
        migrations.AddField(
            model_name='estancias',
            name='diasMinimosLegales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='estancias',
            name='especialidadesEnEstancias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.EspecialidadesEnEstancias'),
        ),
        migrations.AddField(
            model_name='estancias',
            name='homologado',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='estancias',
            name='nivelesEstancias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.NivelesEstancias'),
        ),
    ]
