# Generated by Django 2.1.15 on 2026-03-09 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0003_auto_20260309_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='estancias',
            name='tiposTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa1891', to='tarifarios.TiposTarifa'),
        ),
    ]
