# Generated by Django 2.1.15 on 2026-03-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0004_estancias_tipostarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='estancias',
            name='uvrs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
