# Generated by Django 2.1.15 on 2026-03-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0005_estancias_uvrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposEstancias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
    ]
