# Generated by Django 2.1.15 on 2026-03-09 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0006_tiposestancias'),
    ]

    operations = [
        migrations.AddField(
            model_name='estancias',
            name='tiposEstancias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.TiposEstancias'),
        ),
    ]
