# Generated by Django 2.1.15 on 2026-03-09 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0006_causasexterna_ripscausaexterna'),
        ('tarifarios', '0007_estancias_tiposestancias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estancias',
            name='nivelesEstancias',
        ),
        migrations.AddField(
            model_name='estancias',
            name='nivelesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.NivelesClinica'),
        ),
    ]
