# Generated by Django 2.1.15 on 2026-03-09 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0006_causasexterna_ripscausaexterna'),
        ('tarifarios', '0008_auto_20260309_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='estancias',
            name='cups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Examenes'),
        ),
    ]
