# Generated by Django 2.1.15 on 2026-01-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinico', '0002_auto_20260123_1105'),
        ('facturacion', '0001_initial'),
        ('rips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suministros',
            name='ripsCums',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsCums01', to='rips.RipsCums'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='ripsDci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsDci01', to='rips.RipsDci'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='ripsFormaFarmaceutica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsFfm01', to='rips.RipsFormaFarmaceutica'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='ripsTipoMedicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsTipo01', to='rips.RipsTipoMedicamento'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='ripsUnidadDispensa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsDispensa01', to='rips.RipsUnidadUpr'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='ripsUnidadMedida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsUnidad01', to='rips.RipsUmm'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='ripsUnidadUpr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsUnidadUpr01', to='rips.RipsUnidadUpr'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='subGrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Subgrupo01i01', to='clinico.Grupos'),
        ),
    ]
