# Generated by Django 2.1.15 on 2026-02-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_auto_20260123_1105'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='suministros',
            index=models.Index(fields=['cums'], name='cums_Idx'),
        ),
    ]
