# Generated by Django 2.1.15 on 2026-03-03 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_auto_20260205_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEnvioDian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='facturacion',
            name='fechaRespuestaDian',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='respuestaDian',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
