# Generated by Django 2.1.15 on 2026-03-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_auto_20260303_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='estadoEnvioDyan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estadoDian20192', to='facturacion.EstadoEnvioDian'),
        ),
    ]
