# Generated by Django 2.1.15 on 2026-03-03 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_auto_20260303_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturacion',
            old_name='estadoEnvioDyan',
            new_name='estadoEnvioDian',
        ),
        migrations.RenameField(
            model_name='facturacion',
            old_name='tipoFacturaDyan',
            new_name='tipoFacturaDian',
        ),
    ]
