# Generated by Django 2.1.15 on 2026-03-09 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0006_causasexterna_ripscausaexterna'),
        ('facturacion', '0007_auto_20260303_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='nivelesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.NivelesClinica'),
        ),
    ]
