# Generated by Django 2.1.15 on 2026-02-12 19:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0002_auto_20260123_1105'),
        ('facturacion', '0004_auto_20260205_1211'),
        ('cartera', '0002_auto_20260123_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosEmpresas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EmpresasPagos73645', to='facturacion.Empresas')),
                ('formaPago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.FormasPagos')),
                ('sedesClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica764145', to='sitios.SedesClinica')),
                ('serviciosAdministrativos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm095', to='sitios.ServiciosAdministrativos')),
                ('tipoPago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cartera.TiposPagos')),
            ],
        ),
        migrations.CreateModel(
            name='PagosEmpresasDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Empresas7645', to='facturacion.Empresas')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Facturacion')),
                ('pagosEmpresas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EmpresasPagos7646', to='cartera.PagosEmpresas')),
            ],
        ),
    ]
