# Generated by Django 2.1.15 on 2026-02-12 19:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_auto_20260205_1211'),
        ('cartera', '0003_pagosempresas_pagosempresasdetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pagos', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('saldo', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('valor', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.Facturacion')),
            ],
        ),
        migrations.AddField(
            model_name='pagosempresas',
            name='radicado',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='pagosempresasdetalle',
            name='radicadoFactura',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pagosempresas',
            name='valor',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pagosempresasdetalle',
            name='valor',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
