# Generated by Django 2.1.15 on 2026-02-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_auto_20260205_1211'),
        ('cartera', '0005_cartera_sedesclinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartera',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Empresas764578', to='facturacion.Empresas'),
        ),
    ]
