# Generated by Django 2.1.15 on 2026-02-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0006_cartera_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagosempresasdetalle',
            name='empresa',
        ),
    ]
