# Generated by Django 2.1.15 on 2026-02-18 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0002_auto_20260123_1105'),
        ('cartera', '0007_remove_pagosempresasdetalle_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosempresasdetalle',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm09588', to='sitios.ServiciosAdministrativos'),
        ),
    ]
