# Generated by Django 2.1.15 on 2026-02-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0008_pagosempresasdetalle_serviciosadministrativos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosempresasdetalle',
            name='radicadoFactura',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
