# Generated by Django 2.1.15 on 2026-02-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0009_auto_20260218_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosempresas',
            name='radicado',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
