# Generated by Django 2.1.15 on 2026-01-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitios', '0001_initial'),
        ('Administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mae_repusuarios',
            name='cod_sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cod_sede', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='mae_repusuarios',
            name='mae_reportes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mae_reportes', to='Administracion.Mae_Reportes'),
        ),
        migrations.AddField(
            model_name='mae_repparametros',
            name='mae_reportes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Administracion.Mae_Reportes'),
        ),
        migrations.AddField(
            model_name='mae_repparametros',
            name='mae_tiposcampo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Administracion.Mae_TiposCampo'),
        ),
        migrations.AddField(
            model_name='mae_reportes',
            name='mae_gruporeportes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Administracion.Mae_GrupoReportes'),
        ),
        migrations.AddField(
            model_name='mae_reportes',
            name='mae_subgruporeportes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Administracion.Mae_SubGrupoReportes'),
        ),
        migrations.AlterUniqueTogether(
            name='imhotep_sedesreportes',
            unique_together={('codreg_sede', 'nom_sede')},
        ),
        migrations.AlterUniqueTogether(
            name='mae_subgruporeportes',
            unique_together={('mae_gruporeportes', 'nom_subgrupo')},
        ),
        migrations.AlterUniqueTogether(
            name='mae_repusuarios',
            unique_together={('cod_sede', 'mae_reportes', 'cod_usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='mae_repparametros',
            unique_together={('mae_reportes', 'parametro')},
        ),
    ]
