# Generated by Django 5.2.14 on 2026-09-03 15:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admisiones', '0002_initial'),
        ('clinico', '0005_initial'),
        ('contratacion', '0003_initial'),
        ('planta', '0002_initial'),
        ('sitios', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoRestriccionAgendas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, editable=False, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosCitasMedicas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, editable=False, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosConsultorios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, editable=False, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosProgramacionCitasMedicas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, editable=False, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TiposAtencion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, editable=False, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TiposCitasMedicas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, editable=False, max_length=30, null=True)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AgendasMedicas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estadoAgenda', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.especialidades')),
                ('especialidadesMedicos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.especialidadesmedicos')),
                ('sedesClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica_333011', to='sitios.sedesclinica')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioRegistroPlanta12', to='planta.planta')),
            ],
        ),
        migrations.CreateModel(
            name='AgendasMedicasProgramacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('atiendeDesde', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atiendeHasta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('desDeHoraDeAlmuerzo', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('hastaDoraDeAlmuerzo', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('duracionCita', models.CharField(choices=[('Veinte', '20 Minutos'), ('Quince', '15 Minutos'), ('Diez', '10 Minutos')], default='Diez', editable=False, max_length=15)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('agendaMedica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='citasMedicas.agendasmedicas')),
                ('sedesClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica_2345301', to='sitios.sedesclinica')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioRegistroPlanta90', to='planta.planta')),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaDia', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('nombre', models.CharField(default='', max_length=30)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('sedesClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica3021', to='sitios.sedesclinica')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioRegistroPlanta349', to='planta.planta')),
            ],
        ),
        migrations.CreateModel(
            name='CitasMedicas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soatAccidente', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1)),
                ('fechaReserva', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaSolicitada', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaAtencion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaCancelada', models.DateTimeField(default=django.utils.timezone.now)),
                ('citaPrimeraVez', models.CharField(default='S', editable=False, max_length=1)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('admision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_01', to='admisiones.ingresos')),
                ('agendasMedicasProgramacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendasMedicasPorgramacion01', to='citasMedicas.agendasmedicasprogramacion')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratacion.convenios')),
                ('furips', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='furips_01', to='admisiones.furips')),
                ('sedesClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica_678301', to='sitios.sedesclinica')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioRegistroPlanta98', to='planta.planta')),
                ('estadosCitasMedicas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='citasMedicas.estadoscitasmedicas')),
                ('tiposAtencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='citasMedicas.tiposatencion')),
            ],
        ),
        migrations.CreateModel(
            name='CitasMedicasDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=0, max_digits=6)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('citasMedicas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citasMedicas01', to='citasMedicas.citasmedicas')),
                ('cups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cupsCitas_01', to='clinico.examenes')),
                ('sedesClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica_67301', to='sitios.sedesclinica')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioRegistroPlanta56', to='planta.planta')),
            ],
        ),
        migrations.CreateModel(
            name='Consultorios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=30)),
                ('dia', models.DateField(default=django.utils.timezone.now)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('consultorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consul01', to='citasMedicas.consultorios')),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependencia1099', to='sitios.dependencias')),
                ('sedesClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica_453011', to='sitios.sedesclinica')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioRegistroPlanta45', to='planta.planta')),
                ('estadosConsultorios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estadosConsul01', to='citasMedicas.estadosconsultorios')),
            ],
        ),
        migrations.AddField(
            model_name='agendasmedicasprogramacion',
            name='consultorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consul102', to='citasMedicas.consultorios'),
        ),
        migrations.CreateModel(
            name='AgendasMedicasRestriccionProgramacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('noAtiendeDesde', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('noAatiendeHasta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('agendasMedicasProgramacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='citasMedicas.agendasmedicasprogramacion')),
                ('sedesClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica_679301', to='sitios.sedesclinica')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioRegistroPlanta58', to='planta.planta')),
                ('estadoRestriccionAgendas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='citasMedicas.estadorestriccionagendas')),
            ],
        ),
        migrations.CreateModel(
            name='CronologiaCitasMedicas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('citasMedicas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citasMedicas21', to='citasMedicas.citasmedicas')),
                ('sedesClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica_45301', to='sitios.sedesclinica')),
                ('usuarioRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioRegistroPlanta76', to='planta.planta')),
                ('estadosCitasMedicas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='citasMedicas.estadoscitasmedicas')),
            ],
        ),
        migrations.AddField(
            model_name='agendasmedicasprogramacion',
            name='estadosProgramacioncitasMedicas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='citasMedicas.estadosprogramacioncitasmedicas'),
        ),
    ]
