# Generated by Django 5.2.14 on 2026-09-03 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citasMedicas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendasmedicasprogramacion',
            old_name='hastaDoraDeAlmuerzo',
            new_name='hastaHoraDeAlmuerzo',
        ),
    ]
