# Generated by Django 5.2.14 on 2026-09-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citasMedicas', '0002_rename_hastadoradealmuerzo_agendasmedicasprogramacion_hastahoradealmuerzo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronologiacitasmedicas',
            name='sedesClinica',
        ),
    ]
