# Generated by Django 5.2.14 on 2026-05-15 23:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinico', '0005_initial'),
        ('contratacion', '0003_initial'),
        ('facturacion', '0003_initial'),
        ('planta', '0002_initial'),
        ('sitios', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSolicita', models.DateTimeField(blank=True, null=True)),
                ('fechaAtendio', models.DateTimeField(blank=True, null=True)),
                ('consec', models.IntegerField()),
                ('consecAdmision', models.IntegerField(default=0)),
                ('hClinica', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo', models.CharField(blank=True, max_length=1000, null=True)),
                ('examenFisico', models.CharField(blank=True, max_length=5000, null=True)),
                ('frecCardiaca', models.CharField(blank=True, max_length=10, null=True)),
                ('frecRespiratoria', models.CharField(blank=True, max_length=10, null=True)),
                ('taSist', models.CharField(blank=True, max_length=10, null=True)),
                ('taDiast', models.CharField(blank=True, max_length=10, null=True)),
                ('taMedia', models.CharField(blank=True, max_length=10, null=True)),
                ('glasgow', models.CharField(blank=True, max_length=10, null=True)),
                ('peso', models.CharField(blank=True, max_length=10, null=True)),
                ('temperatura', models.CharField(blank=True, max_length=10, null=True)),
                ('estatura', models.CharField(blank=True, max_length=10, null=True)),
                ('glucometria', models.CharField(blank=True, max_length=50, null=True)),
                ('saturacion', models.CharField(blank=True, max_length=50, null=True)),
                ('escalaDolor', models.CharField(blank=True, max_length=50, null=True)),
                ('vistobno', models.CharField(blank=True, max_length=50, null=True)),
                ('tipoTrauma', models.CharField(blank=True, max_length=50, null=True)),
                ('cinematicaTrauma', models.CharField(blank=True, max_length=50, null=True)),
                ('tipoIngreso', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaModanexo', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.CharField(default='', max_length=5000)),
                ('alergiasTriage', models.CharField(default='', max_length=50)),
                ('salidaDefinitiva', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1)),
                ('fechaRegistro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('causaExterna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.causasexterna')),
                ('clasificacionTriage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.tipostriage')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratacion.convenios')),
                ('dependencias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depCli01', to='sitios.dependencias')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento1', to='usuarios.usuarios')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.empresas')),
                ('enfermedaActual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.enfermedades')),
                ('regimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.regimenes')),
                ('sedesClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica1', to='sitios.sedesclinica')),
                ('serviciosAdministrativos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm02', to='sitios.serviciosadministrativos')),
                ('serviciosSedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Serv21', to='sitios.serviciossedes')),
                ('subServiciosSedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SubServ21', to='sitios.subserviciossedes')),
                ('tipoDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento')),
                ('usuarioAtiende', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento2', to='planta.planta')),
                ('usuarioAutoriza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta')),
                ('usuarioCrea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento3', to='planta.planta')),
                ('viaEgreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.viasegreso')),
            ],
            options={
                'unique_together': {('tipoDoc', 'documento', 'consecAdmision')},
            },
        ),
    ]
