# Generated by Django 2.1.15 on 2026-02-23 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0002_auto_20260123_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadSalas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('año', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('dia', models.IntegerField(blank=True, null=True)),
                ('desdeHora', models.IntegerField(blank=True, null=True)),
                ('hastaHora', models.IntegerField(blank=True, null=True)),
                ('estadoSala', models.CharField(choices=[('L', 'Activo'), ('M', 'Mantenimiento')], default='A', editable=False, max_length=1)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='L', editable=False, max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='salas',
            name='finServicio',
        ),
        migrations.RemoveField(
            model_name='salas',
            name='iniciaServicio',
        ),
        migrations.AddField(
            model_name='disponibilidadsalas',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Salas'),
        ),
    ]
