# Generated by Django 2.1.15 on 2026-02-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0003_auto_20260223_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadsalas',
            name='desdeHora',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidadsalas',
            name='hastaHora',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
