# Generated by Django 2.1.15 on 2026-02-24 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0004_auto_20260223_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponibilidadsalas',
            old_name='sala',
            new_name='salas',
        ),
        migrations.RemoveField(
            model_name='disponibilidadsalas',
            name='año',
        ),
        migrations.RemoveField(
            model_name='disponibilidadsalas',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='disponibilidadsalas',
            name='estadoSala',
        ),
        migrations.RemoveField(
            model_name='disponibilidadsalas',
            name='mes',
        ),
        migrations.AddField(
            model_name='disponibilidadsalas',
            name='estadoDisponiblidad',
            field=models.CharField(choices=[('L', 'Libre'), ('O', 'Ocupado'), ('M', 'Mantenimiento')], default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='disponibilidadsalas',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
