# Generated by Django 2.1.15 on 2026-02-24 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0005_auto_20260224_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponibilidadsalas',
            old_name='estadoDisponiblidad',
            new_name='estadoDisponibilidad',
        ),
        migrations.AlterField(
            model_name='disponibilidadsalas',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
