# Generated by Django 2.1.15 on 2026-02-25 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0006_auto_20260224_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subserviciossedes',
            name='serviciosSedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.ServiciosSedes'),
        ),
    ]
