# Generated by Django 2.1.15 on 2026-03-09 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0007_estancias_tiposestancias'),
        ('sitios', '0007_auto_20260225_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencias',
            name='tiposEstancias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.TiposEstancias'),
        ),
    ]
