# Generated by Django 2.1.15 on 2026-03-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0008_dependencias_tiposestancias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependencias',
            name='tiposEstancias',
        ),
    ]
