# Generated by Django 5.2.14 on 2026-05-15 23:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=80, null=True)),
                ('vigenciaDesde', models.DateField()),
                ('vigenciaHasta', models.DateField()),
                ('porcTarifario', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcSuministros', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valorOxigeno', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('porcEsterilizacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcMaterial', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hospitalario', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True)),
                ('urgencias', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True)),
                ('ambulatorio', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True)),
                ('consultaExterna', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True)),
                ('copago', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True)),
                ('moderadora', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True)),
                ('tipofactura', models.CharField(blank=True, max_length=1, null=True)),
                ('particular', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True)),
                ('agrupada', models.CharField(blank=True, max_length=1, null=True)),
                ('facturacionSuministros', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True)),
                ('facturacionCups', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True)),
                ('cuentaContable', models.CharField(blank=True, max_length=20, null=True)),
                ('requisitos', models.CharField(blank=True, max_length=2000, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ConveniosLiquidacionTarifasHonorarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoHomologado', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ConveniosSuministros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ConveniosTarifasHonorarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoHomologado', models.CharField(blank=True, max_length=10, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
    ]
