# Generated by Django 5.2.14 on 2026-05-15 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinico', '0005_initial'),
        ('contratacion', '0002_initial'),
        ('facturacion', '0002_initial'),
        ('planta', '0001_initial'),
        ('sitios', '0001_initial'),
        ('tarifarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm315', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='tarifariosDescripcionHono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TarifariosDescripcionHonor0124', to='tarifarios.tarifariosdescripcionhonorarios'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='tarifariosDescripcionProc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TarifariosDescripcion0121', to='tarifarios.tarifariosdescripcion'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='tarifariosDescripcionSum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TarifariosDescripcion0123', to='tarifarios.tarifariosdescripcion'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AddField(
            model_name='conveniosliquidaciontarifashonorarios',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Concepto224', to='facturacion.conceptos'),
        ),
        migrations.AddField(
            model_name='conveniosliquidaciontarifashonorarios',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratacion.convenios'),
        ),
        migrations.AddField(
            model_name='conveniosliquidaciontarifashonorarios',
            name='cups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups209', to='clinico.examenes'),
        ),
        migrations.AddField(
            model_name='conveniosliquidaciontarifashonorarios',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm18', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='conveniosliquidaciontarifashonorarios',
            name='suministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Suminis1277', to='facturacion.suministros'),
        ),
        migrations.AddField(
            model_name='conveniosliquidaciontarifashonorarios',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario017', to='tarifarios.tiposhonorarios'),
        ),
        migrations.AddField(
            model_name='conveniosliquidaciontarifashonorarios',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoTarifa037', to='tarifarios.tipostarifa'),
        ),
        migrations.AddField(
            model_name='conveniosliquidaciontarifashonorarios',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantas2177', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='conveniossuministros',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratacion.convenios'),
        ),
        migrations.AddField(
            model_name='conveniossuministros',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm17', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='conveniossuministros',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AddField(
            model_name='conveniostarifashonorarios',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratacion.convenios'),
        ),
        migrations.AddField(
            model_name='conveniostarifashonorarios',
            name='cups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups215', to='clinico.examenes'),
        ),
        migrations.AddField(
            model_name='conveniostarifashonorarios',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm16', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='conveniostarifashonorarios',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario05', to='tarifarios.tiposhonorarios'),
        ),
        migrations.AddField(
            model_name='conveniostarifashonorarios',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.tipostarifa'),
        ),
        migrations.AddField(
            model_name='conveniostarifashonorarios',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AlterUniqueTogether(
            name='conveniostarifashonorarios',
            unique_together={('convenio', 'tipoTarifa', 'tipoHonorario')},
        ),
    ]
