# Generated by Django 5.2.14 on 2026-05-15 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admisiones', '0002_initial'),
        ('cartera', '0002_initial'),
        ('clinico', '0005_initial'),
        ('planta', '0002_initial'),
        ('rips', '0001_initial'),
        ('sitios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsenvios',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica759', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='ripsenvios',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm26', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='ripsenvios',
            name='usuarioEnvia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planta145', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='ripsenvios',
            name='usuarioGeneraJson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planta146', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='ripsenvios',
            name='usuarioRadicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planta149', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='ripsenvios',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AddField(
            model_name='ripsdetalle',
            name='ripsEnvios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Envios01', to='rips.ripsenvios'),
        ),
        migrations.AddField(
            model_name='ripsenvios',
            name='ripsEstados',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsEstados02', to='rips.ripsestados'),
        ),
        migrations.AddField(
            model_name='ripsdetalle',
            name='ripsEstados',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsEtados01', to='rips.ripsestados'),
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='finalidadTecnologiaSalud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Final01', to='rips.ripsfinalidadconsulta'),
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='grupoServicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Grupo01', to='rips.ripsgruposervicios'),
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='modalidadGrupoServicioTecSal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modal01', to='rips.ripsgruposervicios'),
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='causaMotivoAtencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CausaExt05', to='rips.ripscausaexterna'),
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='codComplicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost36', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='codDiagnosticoCausaMuerte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost37', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='codDiagnosticoPrincipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost31', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='codDiagnosticoPrincipalE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost32', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='codDiagnosticoRelacionadoE1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost33', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='codDiagnosticoRelacionadoE2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost34', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='codDiagnosticoRelacionadoE3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost35', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='condicionDestinoUsuarioEgreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DestinoUsu02', to='rips.ripsdestinoegreso'),
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingre_06', to='admisiones.ingresos'),
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsDetalle09', to='rips.ripsdetalle'),
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Plantas21', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='codDiagnosticoPrincipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost51', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='codDiagnosticoRelacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost52', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='codTecnologiaSalud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cums01', to='rips.ripscums'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='conceptoRecaudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Recaudo41', to='rips.ripsconceptorecaudo'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='formaFarmaceutica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Farmaceu01', to='rips.ripsformafarmaceutica'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='glosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Glosas06', to='cartera.glosas'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingre_09', to='admisiones.ingresos'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='notaCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaCredito00304', to='cartera.notascredito'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsDetalle07', to='rips.ripsdetalle'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Plantas61', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='codTecnologiaSalud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsCums11', to='rips.ripscums'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='codTecnologiaSaludCups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsCups11', to='clinico.examenes'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='conceptoRecaudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Recaudo50', to='rips.ripsconceptorecaudo'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='glosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Glosas07', to='cartera.glosas'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingre_10', to='admisiones.ingresos'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='notaCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaCredito00214', to='cartera.notascredito'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsDetalle06', to='rips.ripsdetalle'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Plantas12', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='codComplicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost12', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='codDiagnosticoPrincipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost10', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='codDiagnosticoRelacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost11', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='codProcedimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Examen05', to='clinico.examenes'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='conceptoRecaudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Recaudo05', to='rips.ripsconceptorecaudo'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='finalidadTecnologiaSalud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Finalidad02', to='rips.ripsfinalidadconsulta'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='glosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Glosas04', to='cartera.glosas'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='grupoServicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GrupoServicios01', to='rips.ripsgruposervicios'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingre_04', to='admisiones.ingresos'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='modalidadGrupoServicioTecSal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ModalServ01', to='rips.ripsmodalidadatencion'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='notaCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotaCredito0003', to='cartera.notascredito'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsDetalle04', to='rips.ripsdetalle'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Plantas02', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='ripsreciennacido',
            name='codDiagnosticoCausaMuerte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost43', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ripsreciennacido',
            name='codDiagnosticoPrincipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost41', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ripsreciennacido',
            name='condicionDestinoUsuarioEgreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost42', to='rips.ripsdestinoegreso'),
        ),
        migrations.AddField(
            model_name='ripsreciennacido',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingre_07', to='admisiones.ingresos'),
        ),
        migrations.AddField(
            model_name='ripsreciennacido',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsDetalle08', to='rips.ripsdetalle'),
        ),
        migrations.AddField(
            model_name='ripsreciennacido',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Plantas33', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='codServicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Serrvicio02', to='rips.ripsservicios'),
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='codServicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Servicio01', to='rips.ripsservicios'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='tipoMedicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoMed01', to='rips.ripstipomedicamento'),
        ),
        migrations.AddField(
            model_name='ripscums',
            name='ripsTipoMedicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsTipo11', to='rips.ripstipomedicamento'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='tipoOS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='OtrosServ01', to='rips.ripstipootrosservicios'),
        ),
        migrations.AddField(
            model_name='ripsreciennacido',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos05', to='rips.ripstipos'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos02', to='rips.ripstipos'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos07', to='rips.ripstipos'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos06', to='rips.ripstipos'),
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos04', to='rips.ripstipos'),
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos01', to='rips.ripstipos'),
        ),
        migrations.AddField(
            model_name='ripsreciennacido',
            name='tipoDocumentoIdentificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoDocRips01', to='rips.ripstiposdocumento'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='tipoDocumentoIdentificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoDocu05', to='rips.ripstiposdocumento'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='tipoDocumentoIdentificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsTiposDoc21', to='rips.ripstiposdocumento'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='tipoDocumentoIdentificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsTiposDoc31', to='rips.ripstiposdocumento'),
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='tipoDocumentoIdentificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.ripstiposdocumento'),
        ),
        migrations.AddField(
            model_name='ripsenvios',
            name='ripsTiposNotas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsTipóNotas01', to='rips.ripstiposnotas'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='tipoPagoModerador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modera01', to='rips.ripstipospagomoderador'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='tipoPagoModerador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modera012', to='rips.ripstipospagomoderador'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='tipoPagoModerador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modera0122', to='rips.ripstipospagomoderador'),
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='tipoPagoModerador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modera031', to='rips.ripstipospagomoderador'),
        ),
        migrations.AddField(
            model_name='ripstransaccion',
            name='ripsEnvio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsDetalle01', to='rips.ripsenvios'),
        ),
        migrations.AddField(
            model_name='ripstransaccion',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica769', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='ripstransaccion',
            name='tipoNota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoNota01', to='rips.ripstiposnotas'),
        ),
        migrations.AddField(
            model_name='ripstransaccion',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AddField(
            model_name='ripsreciennacido',
            name='ripsTransaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpipsTransaccion18', to='rips.ripstransaccion'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='ripsTransaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpipsTransaccion14', to='rips.ripstransaccion'),
        ),
        migrations.AddField(
            model_name='ripsotrosservicios',
            name='ripsTransaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpipsTransaccion20', to='rips.ripstransaccion'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='ripsTransaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpipsTransaccion19', to='rips.ripstransaccion'),
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='ripsTransaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpipsTransaccion17', to='rips.ripstransaccion'),
        ),
        migrations.AddField(
            model_name='ripsconsultas',
            name='ripsTransaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpipsTransaccion13', to='rips.ripstransaccion'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='unidadMedida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Umedida11', to='rips.ripsumm'),
        ),
        migrations.AddField(
            model_name='ripscums',
            name='ripsUnidadMedida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsUnidad12', to='rips.ripsumm'),
        ),
        migrations.AddField(
            model_name='ripsmedicamentos',
            name='unidadMinDispensa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='UnidadUpr01', to='rips.ripsunidadupr'),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='causaMotivoAtencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.ripscausaexterna'),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='codDiagnosticoCausaMuerte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost26', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='codDiagnosticoPrincipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost21', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='codDiagnosticoPrincipalE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost22', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='codDiagnosticoRelacionadoE1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost23', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='codDiagnosticoRelacionadoE2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost24', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='codDiagnosticoRelacionadoE3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Diagnost25', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='condicionDestinoUsuarioEgreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DestinoEgre01', to='rips.ripsdestinoegreso'),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingre_05', to='admisiones.ingresos'),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsDetalle05', to='rips.ripsdetalle'),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos03', to='rips.ripstipos'),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='ripsTransaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpipsTransaccion15', to='rips.ripstransaccion'),
        ),
        migrations.AddField(
            model_name='ripsurgenciasobservacion',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Plantas05', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='ripsusuarios',
            name='codMunicipioResidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MunicipioRes01', to='sitios.municipios'),
        ),
        migrations.AddField(
            model_name='ripsusuarios',
            name='codPaisOrigen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.ripspaises'),
        ),
        migrations.AddField(
            model_name='ripsusuarios',
            name='codPaisResidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Paises01', to='rips.ripspaises'),
        ),
        migrations.AddField(
            model_name='ripsusuarios',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingre_02', to='admisiones.ingresos'),
        ),
        migrations.AddField(
            model_name='ripsusuarios',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsDetalle02', to='rips.ripsdetalle'),
        ),
        migrations.AddField(
            model_name='ripsusuarios',
            name='ripsTransaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpipsTransaccion12', to='rips.ripstransaccion'),
        ),
        migrations.AddField(
            model_name='ripsusuarios',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Usu01', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='ripscums',
            name='ripsViasAdministracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ViasAdmon10', to='rips.ripsviasadministracion'),
        ),
        migrations.AddField(
            model_name='ripsprocedimientos',
            name='viaIngresoServicioSalud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='IngresoSal01', to='rips.ripsviasingresosalud'),
        ),
        migrations.AddField(
            model_name='ripshospitalizacion',
            name='viaIngresoServicioSalud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='IngresoSal11', to='rips.ripsviasingresosalud'),
        ),
        migrations.AddField(
            model_name='ripsusuarios',
            name='codZonaTerritorialResidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SonaRes01', to='rips.ripszonaterritorial'),
        ),
    ]
