# Generated by Django 5.2.14 on 2026-05-15 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratacion', '0002_initial'),
        ('facturacion', '0001_initial'),
        ('planta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptosafacturar',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AddField(
            model_name='conveniospacienteingresos',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convenios0221', to='contratacion.convenios'),
        ),
    ]
