# Generated by Django 5.2.14 on 2026-05-15 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autorizaciones', '0004_initial'),
        ('cartera', '0002_initial'),
        ('cirugia', '0003_initial'),
        ('clinico', '0005_initial'),
        ('contratacion', '0003_initial'),
        ('facturacion', '0002_initial'),
        ('planta', '0001_initial'),
        ('rips', '0001_initial'),
        ('sitios', '0001_initial'),
        ('tarifarios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveniospacienteingresos',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria2', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='conveniospacienteingresos',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='conveniospacienteingresos',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AddField(
            model_name='eapb',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Ciudada0001', to='sitios.ciudades'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Depto01', to='sitios.departamentos'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Muni01', to='sitios.municipios'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='nivelesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.nivelesclinica'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.regimenes'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Conv08', to='contratacion.convenios'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoFac2', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='estadoEnvioDian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estadoDian20192', to='facturacion.estadoenviodian'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='ripsEnvio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.ripsenvios'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica398', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm20', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TiposDoc101', to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='usuarioAnula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Plantas100', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Plantas101', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='conveniospacienteingresos',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.facturacion'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='autorizacionDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AutDet101', to='autorizaciones.autorizacionesdetalle'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Ciru01112', to='cirugia.cirugias'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Conceptos1115', to='facturacion.conceptos'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TablaCups121', to='clinico.examenes'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='facturacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Fact01', to='facturacion.facturacion'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='glosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TablaCups129', to='cartera.glosas'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='historiaMedicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='histmed01', to='clinico.historiamedicamentos'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='notaCredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TablaCups121', to='cartera.notascredito'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='notaDebito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TablaCups121', to='cartera.notasdebito'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='ripsDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.ripsdetalle'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='ripsTipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RpsTipos108', to='rips.ripstipos'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario099', to='tarifarios.tiposhonorarios'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='usuarioCrea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta105', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='usuarioModifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta106', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta107', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Convenio102', to='contratacion.convenios'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoFac3', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica789', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm21', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TiposDoc120', to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='usuarioAnula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta108', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta109', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='liquidacioncirugias',
            name='tipoTarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.tipostarifa'),
        ),
        migrations.AddField(
            model_name='liquidacioncirugias',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='autorizacionDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AutDet102', to='autorizaciones.autorizacionesdetalle'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Ciru0111', to='cirugia.cirugias'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Conceptos0005', to='facturacion.conceptos'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TablaCups101', to='clinico.examenes'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='historiaMedicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='histmed02', to='clinico.historiamedicamentos'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='liquidacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Liquid01', to='facturacion.liquidacion'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario091', to='tarifarios.tiposhonorarios'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='usuarioModifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planat121', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta122', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='prefijosdian',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica5589', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='consecutivosdian',
            name='prefijoDian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prefijodian667', to='facturacion.prefijosdian'),
        ),
        migrations.AddField(
            model_name='refacturacion',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoFac4', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='refacturacion',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica667', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='refacturacion',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm51', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='refacturacion',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TiposDoc145', to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='refacturacion',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta123', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='regimenestipopago',
            name='regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.regimenes'),
        ),
        migrations.AddField(
            model_name='regimenestipopago',
            name='salarioLegal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.salarioslegales'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='concentracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.medicamentosdci'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.conceptos'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.grupos'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='principioActivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.principiosactivos'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='ripsCums',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsCums01', to='rips.ripscums'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='ripsDci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsDci01', to='rips.ripsdci'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='ripsFormaFarmaceutica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsFfm01', to='rips.ripsformafarmaceutica'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='ripsTipoMedicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsTipo01', to='rips.ripstipomedicamento'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='ripsUnidadDispensa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsDispensa01', to='rips.ripsunidadupr'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='ripsUnidadMedida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsUnidad01', to='rips.ripsumm'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='ripsUnidadUpr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsUnidadUpr01', to='rips.ripsunidadupr'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='subGrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Subgrupo01i01', to='clinico.grupos'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='tipoHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.tiposhonorarios'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='unidadMedida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.ripsumm'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='viaAdministracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.viasadministracion'),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='cums',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Suministros05', to='facturacion.suministros'),
        ),
        migrations.AddField(
            model_name='facturaciondetalle',
            name='cums',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Sum102', to='facturacion.suministros'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='tipoEmpresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.tiposempresa'),
        ),
        migrations.AddField(
            model_name='tipossuministro',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.conceptos'),
        ),
        migrations.AddField(
            model_name='tipossuministro',
            name='tiposHonorarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.tiposhonorarios'),
        ),
        migrations.AddField(
            model_name='suministros',
            name='tipoSuministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.tipossuministro'),
        ),
        migrations.AlterUniqueTogether(
            name='conveniospacienteingresos',
            unique_together={('tipoDoc', 'documento', 'consecAdmision', 'convenio')},
        ),
        migrations.AddIndex(
            model_name='suministros',
            index=models.Index(fields=['nombre'], name='suministrosNombreIdx'),
        ),
        migrations.AddIndex(
            model_name='suministros',
            index=models.Index(fields=['cums'], name='cums_Idx'),
        ),
    ]
