# Generated by Django 5.2.14 on 2026-05-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='contacto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
