# Generated by Django 2.1.15 on 2026-03-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0002_auto_20260123_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='RipsTipoDiagnosticoPrincipal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
