# Generated by Django 2.1.15 on 2026-03-04 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0003_ripstipodiagnosticoprincipal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripsotrosservicios',
            name='codTecnologiaSaludCups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RipsCups11', to='clinico.Examenes'),
        ),
    ]
