# Generated by Django 2.1.15 on 2026-03-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0004_auto_20260304_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsconsultas',
            name='tipoPagoModerador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modera031', to='rips.RipsTiposPagoModerador'),
        ),
    ]
