# Generated by Django 2.1.15 on 2026-02-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0003_auto_20260123_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirugias',
            name='solicitaAnestesia',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
    ]
