# Generated by Django 5.2.14 on 2026-05-15 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admisiones', '0001_initial'),
        ('autorizaciones', '0004_initial'),
        ('basicas', '0002_initial'),
        ('clinico', '0004_initial'),
        ('facturacion', '0002_initial'),
        ('planta', '0001_initial'),
        ('rips', '0001_initial'),
        ('sitios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furips',
            name='departamentoEvento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dept10', to='sitios.departamentos'),
        ),
        migrations.AddField(
            model_name='furips',
            name='departamentoInvolucrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dept12', to='sitios.departamentos'),
        ),
        migrations.AddField(
            model_name='furips',
            name='departamentoPropietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dept11', to='sitios.departamentos'),
        ),
        migrations.AddField(
            model_name='furips',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documentofur', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='furips',
            name='documentoProfesionalAtendio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AddField(
            model_name='furips',
            name='documentoVictima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento14', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='furips',
            name='dxPrincEgreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx4', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='furips',
            name='dxPrincIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx1', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='furips',
            name='dxRel1Egreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx5', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='furips',
            name='dxRel1Ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx2', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='furips',
            name='dxRel2Egreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx6', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='furips',
            name='dxRel2Ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dx3', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='furips',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicas.eventos'),
        ),
        migrations.AddField(
            model_name='furips',
            name='localidadEvento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local09', to='sitios.localidades'),
        ),
        migrations.AddField(
            model_name='furips',
            name='localidadInvolucrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.localidades'),
        ),
        migrations.AddField(
            model_name='furips',
            name='localidadPropietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local10', to='sitios.localidades'),
        ),
        migrations.AddField(
            model_name='furips',
            name='municipioEvento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muni10', to='sitios.municipios'),
        ),
        migrations.AddField(
            model_name='furips',
            name='municipioInvolucrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muni12', to='sitios.municipios'),
        ),
        migrations.AddField(
            model_name='furips',
            name='municipioPropietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muni11', to='sitios.municipios'),
        ),
        migrations.AddField(
            model_name='furips',
            name='prestadorRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ips86', to='clinico.ips'),
        ),
        migrations.AddField(
            model_name='furips',
            name='prestadorRemite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ips7', to='clinico.ips'),
        ),
        migrations.AddField(
            model_name='furips',
            name='profesionalRemite',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planta112', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='furips',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica3', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='furips',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='furips',
            name='tipoDocInvolucrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipoDoc15', to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='furips',
            name='tipoDocProfesionalAtendio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipoDoc16', to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='furips',
            name='tipoDocPropietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipoDoc17', to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='furips',
            name='tipoDocVictima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipoDoc14', to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='furips',
            name='usuarioCrea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planta111', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ViasEgreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.viasegreso'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ViasIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.viasingreso'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='autorizacionesAmbDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autAmb01', to='autorizaciones.autorizacionesdetalle'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='autorizacionesConsultaDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autCons01', to='autorizaciones.autorizacionesdetalle'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='autorizacionesHospitalDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autHosp01', to='autorizaciones.autorizacionesdetalle'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='autorizacionesUrgenciasDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autUrg01', to='autorizaciones.autorizacionesdetalle'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='causasExterna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.causasexterna'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='contactoAcompañante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Contac01', to='usuarios.usuarioscontacto'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='contactoResponsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Contac02', to='usuarios.usuarioscontacto'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dependenciasActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id1', to='sitios.dependencias'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dependenciasIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id0', to='sitios.dependencias'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dependenciasSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id2', to='sitios.dependencias'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dxActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id4', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dxComplicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id75', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dxIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id3', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dxSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id5', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.empresas'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='especialidadesMedicosActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EspAct', to='clinico.especialidadesmedicos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='especialidadesMedicosIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EspIng', to='clinico.especialidadesmedicos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='especialidadesMedicosSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EspSal', to='clinico.especialidadesmedicos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='estadoSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.estadossalida'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ipsRemite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.ips'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='medicoActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id7', to='clinico.medicos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='medicoDefuncion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.medicos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='medicoIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id6', to='clinico.medicos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='medicoSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id8', to='clinico.medicos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.regimenes'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsCausaMotivoAtencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.ripscausaexterna'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsCodServicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.ripsservicios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsCondicionDestinoUsuarioEgreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripssServicios10', to='rips.ripsdestinoegreso'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsDestinoUsuarioEgresoRecienNacido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripssDestino12', to='rips.ripsdestinoegreso'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsFinalidadConsulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.ripsfinalidadconsulta'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsGrupoServicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.ripsgruposervicios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsServiciosActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripssServicios02', to='rips.ripsservicios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsServiciosIng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripssServicios01', to='rips.ripsservicios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsServiciosSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripssServicios03', to='rips.ripsservicios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsTipoUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ripsTipousuario12', to='rips.ripstipousuario'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsViaIngresoServicioSalud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.ripsviasingresosalud'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='ripsmodalidadGrupoServicioTecSal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.ripsmodalidadatencion'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='salidaMotivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidaMotivo01', to='clinico.tipossalidas'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='serviciosActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id10', to='sitios.serviciossedes'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm01', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='serviciosIng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id9', to='sitios.serviciossedes'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='serviciosSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id11', to='sitios.serviciossedes'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='tiposCotizante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.tiposcotizante'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AlterUniqueTogether(
            name='ingresos',
            unique_together={('tipoDoc', 'documento', 'consec')},
        ),
    ]
