# Generated by Django 5.2.14 on 2026-05-15 23:03

import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basicas', '0002_initial'),
        ('rips', '0001_initial'),
        ('sitios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abreviatura', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=50)),
                ('tiposDocCodigoDian', models.CharField(default='', max_length=15)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('tipoDocRips', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.ripstiposdocumento')),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosContacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='L', max_length=1)),
                ('fechaNacio', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('ciudades', smart_selects.db_fields.ChainedForeignKey(chained_field='departamentos', chained_model_field='departamentos', on_delete=django.db.models.deletion.CASCADE, to='sitios.ciudades')),
                ('departamentos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.departamentos')),
                ('tipoDoc', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tipoDoc01', to='usuarios.tiposdocumento')),
                ('tiposContacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicas.tiposcontacto')),
                ('tiposFamilia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicas.tiposfamilia')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=80)),
                ('primerNombre', models.CharField(blank=True, max_length=20, null=True)),
                ('segundoNombre', models.CharField(blank=True, max_length=20, null=True)),
                ('primerApellido', models.CharField(blank=True, max_length=20, null=True)),
                ('segundoApellido', models.CharField(blank=True, max_length=20, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('fechaNacio', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', editable=False, max_length=1)),
                ('centrosC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.centros')),
                ('ciudades', smart_selects.db_fields.ChainedForeignKey(chained_field='departamentos', chained_model_field='departamentos', on_delete=django.db.models.deletion.CASCADE, to='sitios.ciudades')),
                ('departamentos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.departamentos')),
                ('estadoCivil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicas.estadocivil')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.localidades')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.municipios')),
                ('ocupacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicas.ocupaciones')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.paises')),
                ('ripsZonaTerritorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.ripszonaterritorial')),
                ('tipoDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento')),
                ('tiposUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposusuario')),
            ],
            options={
                'unique_together': {('tipoDoc', 'documento')},
            },
        ),
    ]
