# Generated by Django 5.2.14 on 2026-05-15 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0002_initial'),
        ('seguridad', '0001_initial'),
        ('sitios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilesclinica',
            name='sedesClinica',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinicaSeguridad', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='perfilesclinicaopciones',
            name='modulosElementosDefId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.moduloselementosdef'),
        ),
        migrations.AddField(
            model_name='perfilesclinicaopciones',
            name='perfilesClinicaId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.perfilesclinica'),
        ),
        migrations.AddField(
            model_name='perfilesgralusu',
            name='perfilesClinicaId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.perfilesclinica'),
        ),
        migrations.AddField(
            model_name='perfilesgralusu',
            name='plantaId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AddField(
            model_name='perfilesopciones',
            name='modulosElementosDefId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.moduloselementosdef'),
        ),
        migrations.AddField(
            model_name='perfilesopciones',
            name='perfilesId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.perfiles'),
        ),
        migrations.AddField(
            model_name='perfilesusu',
            name='perfilesClinicaOpcionesId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.perfilesclinicaopciones'),
        ),
        migrations.AddField(
            model_name='perfilesusu',
            name='plantaId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
    ]
