# Generated by Django 5.2.14 on 2026-05-15 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinico', '0003_initial'),
        ('enfermeria', '0001_initial'),
        ('planta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceliquidosenfermeria',
            name='adminMañana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin001', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='balanceliquidosenfermeria',
            name='adminNoche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin003', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='balanceliquidosenfermeria',
            name='adminTarfe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin002', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='balanceliquidosenfermeria',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HistoriaBalanceLiquidosEnfermeria01', to='clinico.historia'),
        ),
    ]
