# Generated by Django 5.2.14 on 2026-05-15 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autorizaciones', '0001_initial'),
        ('contratacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizaciones',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convenios02271', to='contratacion.convenios'),
        ),
    ]
