# Generated by Django 5.2.14 on 2026-05-15 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admisiones', '0001_initial'),
        ('autorizaciones', '0002_initial'),
        ('clinico', '0001_initial'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizaciones',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa765', to='facturacion.empresas'),
        ),
        migrations.AddField(
            model_name='autorizaciones',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Historia476', to='clinico.historia'),
        ),
        migrations.AddField(
            model_name='autorizaciones',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adm1476', to='admisiones.ingresos'),
        ),
    ]
