# Generated by Django 5.2.14 on 2026-05-15 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autorizaciones', '0004_initial'),
        ('cirugia', '0003_initial'),
        ('clinico', '0005_initial'),
        ('facturacion', '0003_initial'),
        ('planta', '0002_initial'),
        ('sitios', '0002_initial'),
        ('triage', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizaciones',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica13', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='autorizaciones',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm03', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='autorizaciones',
            name='triage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Triage1476', to='triage.triage'),
        ),
        migrations.AddField(
            model_name='autorizaciones',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta2', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='autorizacionescirugias',
            name='autorizacionesId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento99', to='autorizaciones.autorizaciones'),
        ),
        migrations.AddField(
            model_name='autorizacionescirugias',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento9', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='autorizacionescirugias',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica5', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='autorizacionescirugias',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='autorizacionescirugias',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioRegistroPlanta2', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='autorizaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento88', to='autorizaciones.autorizaciones'),
        ),
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CiruAut0001', to='cirugia.cirugias'),
        ),
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='cums',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Suminist304', to='facturacion.suministros'),
        ),
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='examenes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Examen829', to='clinico.examenes'),
        ),
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='historiaMedicamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AutMed01', to='clinico.historiamedicamentos'),
        ),
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='tipoSuministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.tipossuministro'),
        ),
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='tiposExamen',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.tiposexamen'),
        ),
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='usuarioRegistro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Planta3', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='autorizacionesdetalle',
            name='estadoAutorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estAut02', to='autorizaciones.estadosautorizacion'),
        ),
        migrations.AddField(
            model_name='autorizaciones',
            name='estadoAutorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='autorizaciones.estadosautorizacion'),
        ),
    ]
