# Generated by Django 2.1.15 on 2026-02-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0003_auto_20260123_1105'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examenes',
            index=models.Index(fields=['codigoCups'], name='cups_Idx'),
        ),
    ]
