# Generated by Django 2.1.15 on 2026-02-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0004_auto_20260205_1213'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historiasignosvitales',
            index=models.Index(fields=['historia'], name='signosVitales_idx1'),
        ),
    ]
