# Generated by Django 2.1.15 on 2026-03-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rips', '0003_ripstipodiagnosticoprincipal'),
        ('clinico', '0005_auto_20260205_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='causasexterna',
            name='ripsCausaExterna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rips.RipsCausaExterna'),
        ),
    ]
