# Generated by Django 2.1.15 on 2026-03-10 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0009_estancias_cups'),
        ('clinico', '0006_causasexterna_ripscausaexterna'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidades',
            name='especialidadesEnEstancias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tarifarios.EspecialidadesEnEstancias'),
        ),
    ]
