# Generated by Django 5.2.14 on 2026-05-15 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autorizaciones', '0004_initial'),
        ('cirugia', '0002_initial'),
        ('clinico', '0004_initial'),
        ('facturacion', '0002_initial'),
        ('planta', '0001_initial'),
        ('sitios', '0001_initial'),
        ('tarifarios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugias',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria54', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='dxComplicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dx555', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='dxPostQx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dx521', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='dxPreQx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dx511', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='dxPrinc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dx531', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='dxRel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dx542', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.especialidades'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='historia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Historia127', to='clinico.historia'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='impresionDx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dx541', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.salas'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm126', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='usuarioCancela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Usuario42', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='usuarioPrograma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Usuario41', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planta39', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='usuarioReprograma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Usuario43', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='usuarioSolicita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Usuario40', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='cirugiasmaterialqx',
            name='autorizacionDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AutMatQx101', to='autorizaciones.autorizacionesdetalle'),
        ),
        migrations.AddField(
            model_name='cirugiasmaterialqx',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.cirugias'),
        ),
        migrations.AddField(
            model_name='cirugiasmaterialqx',
            name='suministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.suministros'),
        ),
        migrations.AddField(
            model_name='cirugiasmaterialqx',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AddField(
            model_name='cirugiasparticipantes',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cirugias13', to='cirugia.cirugias'),
        ),
        migrations.AddField(
            model_name='cirugiasparticipantes',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario12', to='clinico.especialidadesmedicos'),
        ),
        migrations.AddField(
            model_name='cirugiasparticipantes',
            name='tipoHonorarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoHonorario12', to='tarifarios.tiposhonorarios'),
        ),
        migrations.AddField(
            model_name='cirugiasparticipantes',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planta68', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='cirugiasprocedimientos',
            name='autorizacionDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AutDetCir101', to='autorizaciones.autorizacionesdetalle'),
        ),
        migrations.AddField(
            model_name='cirugiasprocedimientos',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cirugias12', to='cirugia.cirugias'),
        ),
        migrations.AddField(
            model_name='cirugiasprocedimientos',
            name='cups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups104', to='clinico.examenes'),
        ),
        migrations.AddField(
            model_name='cirugiasprocedimientos',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planta67', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='cirugiasparticipantes',
            name='cirugiaProcedimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CiruProc10', to='cirugia.cirugiasprocedimientos'),
        ),
        migrations.AddField(
            model_name='cirugiasmaterialqx',
            name='cirugiaProcedimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.cirugiasprocedimientos'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='estadoCirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.estadoscirugias'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='estadoProgramacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.estadosprogramacion'),
        ),
        migrations.AddField(
            model_name='cirugiasprocedimientos',
            name='finalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Final004', to='cirugia.finalidadcirugia'),
        ),
        migrations.AddField(
            model_name='cirugiasparticipantes',
            name='finalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Final005', to='cirugia.finalidadcirugia'),
        ),
        migrations.AddField(
            model_name='hojasdegastos',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cirugias17', to='cirugia.cirugias'),
        ),
        migrations.AddField(
            model_name='hojasdegastos',
            name='suministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.suministros'),
        ),
        migrations.AddField(
            model_name='hojasdegastos',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cir212', to='cirugia.cirugias'),
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria123', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='estadoProgramacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.estadosprogramacion'),
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.salas'),
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seradm129', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='programacioncirugias',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AddField(
            model_name='recordanestesico',
            name='cirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.cirugias'),
        ),
        migrations.AddField(
            model_name='recordanestesico',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AddField(
            model_name='cirugiasprocedimientos',
            name='regionOperatoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups104', to='cirugia.regionesoperatorias'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='anestesia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.tiposanestesia'),
        ),
        migrations.AddField(
            model_name='cirugias',
            name='tiposCirugia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cirugia.tiposcirugia'),
        ),
        migrations.AddField(
            model_name='cirugiasprocedimientos',
            name='viasDeAcceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cups104', to='cirugia.viasdeacceso'),
        ),
    ]
