# Generated by Django 2.1.15 on 2026-01-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitios', '0001_initial'),
        ('planta', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='sedesClinica',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plid1', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='planta',
            name='tipoDoc',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='planta',
            name='tiposPlanta',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.TiposPlanta'),
        ),
        migrations.AlterUniqueTogether(
            name='planta',
            unique_together={('tipoDoc', 'documento', 'nombre')},
        ),
    ]
