# Generated by Django 5.2.14 on 2026-05-15 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autorizaciones', '0004_initial'),
        ('clinico', '0005_initial'),
        ('enfermeria', '0003_initial'),
        ('facturacion', '0003_initial'),
        ('farmacia', '0001_initial'),
        ('planta', '0001_initial'),
        ('sitios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica390', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='serviciosAdministrativos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servAdmFarm01', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='tipoMovimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoEnfermeria05', to='enfermeria.enfermeriatipomovimiento'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='tipoOrigen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TipoEnfermeria04', to='enfermeria.enfermeriatipoorigen'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3450', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='farmaciadespachos',
            name='farmacia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FarmaDespacho02', to='farmacia.farmacia'),
        ),
        migrations.AddField(
            model_name='farmaciadespachos',
            name='serviciosAdministrativosEntrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servAdmFarm02', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='farmaciadespachos',
            name='serviciosAdministrativosRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servAdmFarm03', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='farmaciadespachos',
            name='usuarioEntrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3472', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='farmaciadespachos',
            name='usuarioRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3473', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='farmaciadespachos',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3452', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='farmaciadespachosdispensa',
            name='despacho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FarmaciaDespachos01', to='farmacia.farmaciadespachos'),
        ),
        migrations.AddField(
            model_name='farmaciadespachosdispensa',
            name='dosisUnidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.unidadesdemedidadosis'),
        ),
        migrations.AddField(
            model_name='farmaciadespachosdispensa',
            name='suministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.suministros'),
        ),
        migrations.AddField(
            model_name='farmaciadespachosdispensa',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PlantaFarmacia2253', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='farmaciadespachosdispensa',
            name='viaAdministracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.viasadministracion'),
        ),
        migrations.AddField(
            model_name='farmaciadetalle',
            name='autorizacionDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AutFarmDet501', to='autorizaciones.autorizacionesdetalle'),
        ),
        migrations.AddField(
            model_name='farmaciadetalle',
            name='dosisUnidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.unidadesdemedidadosis'),
        ),
        migrations.AddField(
            model_name='farmaciadetalle',
            name='farmacia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Farmacia01', to='farmacia.farmacia'),
        ),
        migrations.AddField(
            model_name='farmaciadetalle',
            name='historiaMedicamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servAdmFarm01', to='clinico.historiamedicamentos'),
        ),
        migrations.AddField(
            model_name='farmaciadetalle',
            name='suministro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.suministros'),
        ),
        migrations.AddField(
            model_name='farmaciadetalle',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3451', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='farmaciadetalle',
            name='viaAdministracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.viasadministracion'),
        ),
        migrations.AddField(
            model_name='farmaciadespachosdispensa',
            name='farmaciaDetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FarmaciaDetalle01', to='farmacia.farmaciadetalle'),
        ),
        migrations.AddField(
            model_name='farmaciadevolucion',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedesClinica39022', to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='farmaciadevolucion',
            name='serviciosAdministrativosDevuelve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servDevuelve331', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='farmaciadevolucion',
            name='serviciosAdministrativosRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servRecibe3231', to='sitios.serviciosadministrativos'),
        ),
        migrations.AddField(
            model_name='farmaciadevolucion',
            name='usuarioDevuelve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PlantaDevuelve453', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='farmaciadevolucion',
            name='usuarioRecibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PlantaRecibe453', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='farmaciadevolucion',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PlantaFarmaciaDev3453', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='farmaciadevoluciondetalle',
            name='farmaciaDespachosDispensa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FarmaciaDespachos21201', to='farmacia.farmaciadespachosdispensa'),
        ),
        migrations.AddField(
            model_name='farmaciadevoluciondetalle',
            name='farmaciaDevolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FarmaciaDevolucion01', to='farmacia.farmaciadevolucion'),
        ),
        migrations.AddField(
            model_name='farmaciadevoluciondetalle',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PlantaFarmaciaDevDet3453', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='farmaciaestados',
            name='usuarioRegistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Planta3459', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Farmaciaestados01', to='farmacia.farmaciaestados'),
        ),
    ]
