# Generated by Django 2.1.15 on 2026-01-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0003_auto_20260123_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmaciadetalle',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterUniqueTogether(
            name='farmaciadetalle',
            unique_together=set(),
        ),
    ]
