# Generated by Django 2.1.15 on 2026-01-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0004_auto_20260129_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='despachado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='farmaciadetalle',
            name='despachado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', editable=False, max_length=1, null=True),
        ),
    ]
